# Exploring Crime in Chicago 2021

In [4]:
# Import dependencies
import pandas as pd
import numpy as np

In [5]:
# Read in .csv file as a Pandas DataFrame
crime_df = pd.read_csv("Resources/Chicago_Crimes_2021.csv")
crime_df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,12343475,JE202728,4/16/2021 20:45,056XX N RIDGE AVE,820,THEFT,$500 AND UNDER,OTHER (SPECIFY),False,False,...,48.0,77,6,NaN,NaN,2021,4/23/2021 16:51,NaN,NaN,NaN
1,12602803,JF125633,10/21/2021 11:00,083XX S STONY ISLAND AVE,500E,OTHER OFFENSE,EAVESDROPPING,OTHER (SPECIFY),False,False,...,8.0,45,26,1188260.0,1849805.0,2021,2/27/2022 15:46,41.742941,-87.585783,"(41.74294124, -87.585783412)"
2,12565821,JE475344,12/11/2021 20:00,077XX S MAY ST,1752,OFFENSE INVOLVING CHILDREN,AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,RESIDENCE,False,True,...,17.0,71,17,1169996.0,1853419.0,2021,9/27/2022 16:46,41.753274,-87.652598,"(41.753274445, -87.652598299)"
3,12540388,JE444591,11/14/2021 6:00,086XX S COTTAGE GROVE AVE,850,THEFT,ATTEMPT THEFT,CONVENIENCE STORE,False,False,...,6.0,44,6,1183071.0,1847869.0,2021,11/21/2021 15:48,41.737751,-87.604856,"(41.737750767, -87.604855911)"
4,12541139,JE445494,11/14/2021 4:00,034XX W 38TH ST,486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,...,12.0,58,08B,1154073.0,1879187.0,2021,11/21/2021 15:48,41.824317,-87.710266,"(41.824316537, -87.710266215)"

In [12]:
# Get the counts of the "Primary Type" of crime committed
counts_crime = crime_df["Primary Type"].value_counts()
counts_crime

THEFT                                40790
BATTERY                              40458
CRIMINAL DAMAGE                      25094
ASSAULT                              20342
DECEPTIVE PRACTICE                   17255
OTHER OFFENSE                        13936
MOTOR VEHICLE THEFT                  10599
WEAPONS VIOLATION                     8980
ROBBERY                               7917
BURGLARY                              6658
NARCOTICS                             5337
CRIMINAL TRESPASS                     3406
OFFENSE INVOLVING CHILDREN            1902
CRIMINAL SEXUAL ASSAULT               1498
SEX OFFENSE                           1088
HOMICIDE                               810
PUBLIC PEACE VIOLATION                 602
ARSON                                  529
STALKING                               370
INTERFERENCE WITH PUBLIC OFFICER       314
LIQUOR LAW VIOLATION                   184
CONCEALED CARRY LICENSE VIOLATION      173
INTIMIDATION                           123
PROSTITUTION                            95
KIDNAPPING                              87
OBSCENITY                               50
GAMBLING                                13
HUMAN TRAFFICKING                       10
NON-CRIMINAL                             4
PUBLIC INDECENCY                         4
OTHER NARCOTIC VIOLATION                 2
Name: Primary Type, dtype: int64